// Generated by https://quicktype.io

export interface PlacesResponse {
  type: string;
  query: string[];
  features: Feature[];
  attribution: string;
}

export interface Feature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: Properties;
  text: string;
  place_name: string;
  matching_text?: string;
  matching_place_name?: string;
  center: number[];
  geometry: Geometry;
  context: Context[];
}

export interface Context {
  id: string;
  wikidata?: string;
  text: string;
  short_code?: ShortCode;
}

export enum ShortCode {
  Es = 'es',
  EsB = 'ES-B',
}

export interface Geometry {
  coordinates: number[];
  type: string;
}

export interface Properties {
  wikidata?: string;
  address?: string;
  category?: string;
  landmark: boolean;
  foursquare: string;
}
